color0 #000000
color1 #ff9090
color10 #90ffb7
color11 #ffc44f
color12 #4292e3
color13 #9d90ff
color14 #4cc7de
color15 #ffffff
color2 #a7f3d0
color3 #fff290
color4 #66abf0
color5 #c5a5c5
color6 #0dc3de
color7 #c0c9e5
color8 #304b66
color9 #ff7182
background #111e2a
cursor #ffffff
cursor_text_color #111e2a
foreground #c0c9e5
url_color #6c9bf5
selection_foreground #ffffff
selection_background #304b66
